# Clippy configuration (relaxed to get CI green)
warns = [
  "clippy::all"
]
allow = [
  "clippy::pedantic",
  "clippy::nursery",
  "clippy::module_name_repetitions",
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc"
]
