# Rustfmt configuration (stable-only options)
max_width = 100
use_small_heuristics = "Max"
use_field_init_shorthand = true
format_code_in_doc_comments = true
reorder_imports = true
wrap_comments = true
newline_style = "Unix"
format_macro_bodies = true
imports_granularity = "Crate"
normalize_doc_attributes = true
normalize_comments = true
format_strings = true
