# cargo-deny configuration
# See: https://embarkstudios.github.io/cargo-deny/checks/index.html
[advisories]
version = 2
ignore = []

[licenses]
# SPDX identifiers of allowed licenses for dependencies. Tweak as needed.
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"

[sources]
