site_name: logparse-rs SDK Documentation
site_description: High-performance, schema-driven log parsing and anonymization — Rust core with first-class Python bindings.
site_dir: site
docs_dir: docs

nav:
  - Overview: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Python SDK:
      - Overview: python/index.md
      - API Reference: python/api.md
      - Anonymization: python/anonymizer.md
      - CSV Helpers: python/csv_helpers.md
  - Rust Core: rust.md
  - Schema: schema.md
  - Environment: env.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: cyan

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/REPO_OWNER/logparse_rs
