[package]
name = "logparse_core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "logparse_core"
crate-type = ["rlib"]

[dependencies]
memchr = "2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
